// Generated by Wrangler by running `wrangler types` (hash: e7edda119c26b0cd87b02a10e4fd6501)
// Runtime types generated with workerd@1.20250310.0 2024-05-12 
interface Env {
	RACES_URL: string;
	SCRAPER_URL: string;
	F1_SCRAPER: Fetcher;
}